version: '3.8'

services:
  # Frontend React application in development mode
  frontend-dev:
    build:
      context: ..
      dockerfile: docker/development.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8000/ws
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../:/app
      - /app/node_modules
    stdin_open: true  # Equivalent to -i in docker run
    tty: true         # Equivalent to -t in docker run