version: '3.8'

services:
  # Frontend React application only
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8000/ws
    volumes:
      - ../:/app
      - /app/node_modules