version: '3.8'

services:
  # Frontend React application in development mode
  frontend:
    build:
      context: ..
      dockerfile: docker/development.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8000/ws
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      - mock-api
    stdin_open: true
    tty: true

  # Mock API server
  mock-api:
    build:
      context: ./development-mock
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./development-mock:/app
      - ../src/utils/mockData.js:/app/mockData.js
    environment:
      - NODE_ENV=development