name: Knowledge Extraction Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/research_orchestrator/knowledge_extraction/**'
      - 'tests/research_orchestrator/knowledge_extraction/**'
      - '.github/workflows/knowledge_extraction_tests.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/research_orchestrator/knowledge_extraction/**'
      - 'tests/research_orchestrator/knowledge_extraction/**'
      - '.github/workflows/knowledge_extraction_tests.yml'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type to run (unit, integration, e2e, property, edge, all)'
        required: false
        default: 'all'
        type: choice
        options:
          - unit
          - integration
          - e2e
          - property
          - edge
          - all

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        test-type: ${{ github.event_name == 'workflow_dispatch' && contains(fromJSON('["unit", "integration", "e2e", "property", "edge", "all"]'), github.event.inputs.test_type) && fromJSON(format('["{0}"]', github.event.inputs.test_type)) || fromJSON('["unit", "integration", "e2e", "property", "edge"]') }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -e .
      
      - name: Run ${{ matrix.test-type }} tests
        run: |
          cd tests/research_orchestrator/knowledge_extraction
          chmod +x run_tests.sh
          PYTHONPATH=$GITHUB_WORKSPACE ./run_tests.sh -t ${{ matrix.test-type }}
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}-${{ matrix.test-type }}
          path: tests/research_orchestrator/knowledge_extraction/test-report.html
          if-no-files-found: ignore

  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -e .
      
      - name: Run benchmarks
        run: |
          cd tests/research_orchestrator/knowledge_extraction
          PYTHONPATH=$GITHUB_WORKSPACE python -m benchmark.run_benchmarks
      
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: tests/research_orchestrator/knowledge_extraction/benchmark/report.html
          if-no-files-found: ignore

  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install pytest-cov
          pip install -e .
      
      - name: Run tests with coverage
        run: |
          cd tests/research_orchestrator/knowledge_extraction
          PYTHONPATH=$GITHUB_WORKSPACE python -m pytest --cov=../../../src/research_orchestrator/knowledge_extraction --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./tests/research_orchestrator/knowledge_extraction/coverage.xml
          flags: knowledge_extraction
          fail_ci_if_error: false